export const CHANGE_ROUTE_TO_QUESTION = "CHANGE_ROUTE_TO_QUESTION";
export const ADD_SCORE = "ADD_SCORE";
export const REMOVE_SCORE = "REMOVE_SCORE";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const PREVIOUS_QUESTION = "PREVIOUS_QUESTION";
